services:
  frontend:
    build: ./frontend
    container_name: shifumi-frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

  backend:
    build:
      context: ./server
    container_name: shifumi-backend
    ports:
      - "4000:4000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
